[package]
name = "repl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
token = { path = "../token" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
