[package]
name = "evaluator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lexer = { path = "../lexer" }
ast = { path = "../ast" }
parser = { path = "../parser" }
object = { path = "../object" }
